# Generated by Django 2.2.3 on 2021-05-27 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
