# Generated by Django 2.2.3 on 2021-05-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210527_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='FirstName',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='LastName',
        ),
        migrations.AddField(
            model_name='profile',
            name='Firstname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='Lastname',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='profile',
            name='Username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Email',
            field=models.EmailField(blank=True, max_length=128),
        ),
    ]
