# Generated by Django 2.2.3 on 2021-06-14 02:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0005_stocklist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockList',
            new_name='StockGroup',
        ),
    ]
