# Generated by Django 2.2.3 on 2021-06-16 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0006_auto_20210614_1019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField()),
                ('Name', models.TextField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.StockGroup')),
            ],
        ),
    ]
