# Generated by Django 2.2.3 on 2021-06-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0007_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Owner',
            new_name='StockGroup',
        ),
    ]
