# Generated by Django 2.2.3 on 2021-06-16 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stockapp', '0008_auto_20210616_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='BrokerGroup',
        ),
        migrations.RenameField(
            model_name='broker',
            old_name='Group',
            new_name='BrokerGroup',
        ),
    ]
