# Generated by Django 2.2.3 on 2021-06-26 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Broker',
            new_name='BrokerGroupItem',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='StockGroup',
        ),
        migrations.AddField(
            model_name='stock',
            name='Capital',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Industry',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='Status',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='StockGroupItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField()),
                ('Name', models.TextField()),
                ('StockGroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.StockGroup')),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stock')),
            ],
        ),
    ]
