# Generated by Django 2.2.3 on 2021-06-26 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0002_auto_20210626_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionalInvestors',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
