# Generated by Django 2.2.3 on 2021-06-26 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0003_auto_20210626_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.TextField()),
                ('Name', models.TextField()),
                ('Capital', models.TextField(blank=True)),
                ('Industry', models.TextField(blank=True)),
                ('Status', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstitutionalInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stock')),
            ],
        ),
    ]
