# Generated by Django 2.2.3 on 2021-06-26 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0004_institutionalinvestors_stock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InstitutionalInvestors',
        ),
    ]
