# Generated by Django 2.2.3 on 2021-06-26 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockapp', '0005_delete_institutionalinvestors'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalInvestors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.TextField()),
                ('sumForeign', models.TextField()),
                ('sumING', models.TextField()),
                ('sumDealer', models.TextField()),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockapp.Stock')),
            ],
        ),
    ]
